enquete/catalogo/urls.py
from django.urls import path
from . import views

app_name = 'catalogo'

urlpatterns = [
    path('', views.index, name='index'),
    path('autor/<str:autor>/texto/<str:titulo>', views.texto, name='texto'),
    path('autor/<str:username>', views.autor, name='autor'),
    path('categoria/<str:nome>', views.categoria, name='categoria'),
    path('escrita', views.escrita, name='escrita'),
    path('publicar', views.publicar, name='publicar'),
    path('deletar', views.deletar, name='deletar'),
    path('categorias', views.categorias, name='categorias'),
    path('editar/<int:texto_id>', views.editar, name='editar'),
    path('alterar_texto', views.alterar_texto, name='alterar_texto'),
    path('cadastro', views.cadastro, name='cadastro'),
    path('criar_conta', views.criar_conta, name='criar_conta'),
    path('editar_perfil', views.editar_perfil, name='editar_perfil'),
    path('alterar_perfil', views.alterar_perfil, name='alterar_perfil'),
    path('alterar_senha', views.alterar_senha, name='alterar_senha'),
    path('alterar_imagem_perfil', views.alterar_imagem_perfil, name='alterar_imagem_perfil'),
    path('remover_imagem_perfil', views.remover_imagem_perfil, name='remover_imagem_perfil'),
]

enquete/enquete/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('catalogo/', include('catalogo.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

enquete/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('enquete',views.EnqueteView.as_view(), name='enquete'),
    path('enquete/<int:pk>', views.DetalhesView.as_view(), name='detalhes'),
    path('enquete/<int:pk>/resultado', views.ResultadoView.as_view(), name='resultado'),
    path('enquete/<int:id_pergunta>/votar', views.votacao, name='votacao'),
    path('autor/<int:id_autor>', views.autor, name='autor'),
]

enquete/main/models.py
from django.db import models
from django.utils import timezone
import datetime

# Create your models here.

class Autor(models.Model):
    nome = models.CharField(max_length = 200)
    cidade = models.CharField(max_length = 200)
    email = models.CharField(max_length = 200)
    class Meta:
        verbose_name_plural = 'autores'
    def __str__(self):
        return self.nome

class Pergunta(models.Model):
    texto = models.CharField(max_length = 200)
    data_publicacao = models.DateTimeField('Data de Publicação')
    autor = models.ForeignKey(Autor, on_delete=models.CASCADE, blank=True, null=True, default=None)
    def __str__(self):
        return self.texto
    def publicada_recentemente(self):
        agora = timezone.now()
        return agora-datetime.timedelta(days=1) <= self.data_publicacao <= agora
    publicada_recentemente.admin_order_field = 'data_publicacao'
    publicada_recentemente.boolean = True
    publicada_recentemente.short_description = 'recentemente publicada?'

class Opcao(models.Model):
    texto = models.CharField(max_length = 200)
    votos = models.IntegerField(default = 0)
    pergunta = models.ForeignKey(Pergunta, on_delete=models.CASCADE)
    def __str__(self):
        return self.texto
    class Meta:
        verbose_name_plural = 'opções'

enquete/main/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Pergunta, Opcao, Autor
from django.urls import reverse
from django.views import generic
from django.utils import timezone
# Create your views here.

def index(request):
    return render(request, 'main/index2.html', {})

class EnqueteView(generic.ListView):
    template_name = 'main/index.html'
    context_object_name = 'ultimas_perguntas'
    def get_queryset(self):
        return Pergunta.objects.filter(
            data_publicacao__lte=timezone.now()
            ).order_by('-data_publicacao')[:5]

class DetalhesView(generic.DetailView):
    model = Pergunta
    template_name = 'main/detalhes.html'
    def get_queryset(self):
        return Pergunta.objects.filter(data_publicacao__lte=timezone.now())

class ResultadoView(generic.DetailView):
    model = Pergunta
    template_name = 'main/resultado.html'

def autor(request, id_autor):
    autor = get_object_or_404(Autor, pk=id_autor)
    context = {
        'autor':autor,
    }
    return render(request, 'main/autor.html', context)

def votacao(request, id_pergunta):
    pergunta = get_object_or_404(Pergunta, pk=id_pergunta)
    try:
        opcao_selecionada = pergunta.opcao_set.get(pk=request.POST['opcao'])
    except (KeyError, Opcao.DoesNotExist):
        context = {
            'pergunta':pergunta,
            'error_message':'Selecione uma opção válida',
        }
        return render(request, 'main/detalhes.html', context)
    else:
        opcao_selecionada.votos += 1
        opcao_selecionada.save()
        return HttpResponseRedirect(reverse('main:resultado', args=(pergunta.id,)))

enquete/main/templates/main/autor.html
<html>
    <head>
        <title>Autor</title>
    </head>
    <body>
        <h1>Enquetes do Autor {{ autor.nome }}</h1>
        <u>Email</u>: {{ autor.email }}<br/>
        <u>Cidade</u>: {{ autor.cidade }}
        {% if autor.pergunta_set.all %}
        <ul>
            {% for pergunta in autor.pergunta_set.all %}
            <li>
                <a href="{% url 'main:detalhes' pergunta.id %}">
                  {{ pergunta.texto }}
                </a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <h3>100 pergunta</h3>
        {% endif %}
    </body>
    <a href="{% url 'main:index' %}">Página Inicial</a>
</html>

enquete/main/templates/main/detalhes.html
<htmL>
    <head>
        <title>App Enquete</title>
    </head>
    <body>
        <h1>Detalhes da pergunta</h1>
        <p>{{ pergunta.texto }}</p>
        <u>Data de publicação</u>: {{ pergunta.data_publicacao }}<br/
        {% if pergunta.autor %}
        <u>Autor</u>: <a href="{% url 'main:autor' pergunta.autor.id %}">{{ pergunta.autor.nome }}</a><br/>
        <u>Email</u>: {{ pergunta.autor.email }}<br/>
        <u>Cidade</u>: {{ pergunta.autor.cidade }}
        {% endif %}
        <form method="post", action="{% url 'main:votacao' pergunta.id %}">
            {% csrf_token %}
            <ul>
                {% for opcao in pergunta.opcao_set.all %}
                <li>
                    <input type="radio" name="opcao" id="opcao{{ forloop.counter }}" value="{{ opcao.id }}">
                    <label for="opcao{{ forloop.counter }}">{{ opcao.texto }}</label><br/>
                </li>
                {% endfor %}
            </ul>
            <input type="submit" value="votar">
        </form>
        <hr/>
        <a href="{% url 'main:resultado' pergunta.id %}">Resultado parcial</a>
        <a href="{% url 'main:index' %}">Página inicial</a>
    </body>
</htmL>

enquete/main/templates/main/index.html
{% load static %}

<html>
    <head>
        <title>App Enquete</title>
        <link rel="stylesheet"type="text/css" href="{% static 'main/style.css' %}">
    </head>
    <body>
        {% if ultimas_perguntas %}
        <h1>Lista de perguntas</h1>
        <ul>
            {% for pergunta in ultimas_perguntas %}
            <li>
                <a href="{% url 'main:detalhes' pergunta.id %}">
                    {{ pergunta.texto }}
                </a>
            </li>
            {% endfor %}
        </ul>
        {% else %}
        <h3>Não há perguntas cadastradas até o momento.</h3>
        {% endif %}

    </body>
</html>

enquete/main/templates/main/index2.html
<html>
    <head>
        <title>Aplicações DSWeb 2020.1</title>
    </head>
    <body>
        <h2>Aplicações da Disciplina DSWeb 2020.1</h2>
        <h4>Selecione a aplicação desejada</h4>
        <ul>
            <li><a href="{% url 'main:enquete' %}">Aplicação Enquete - Módulo 1</a></li>
            <li><a href="{% url 'catalogo:index' %}">Aplicação Catálogo - Módulo 2</a></li>
        </ul>
        <hr>
        <b>Viviane Matias</b> (<i>srm.12@outlook.com</i>)
    </body>
</html>

enquete/main/templates/main/resultado.html
<htmL>
    <head>
        <title>App Enquete</title>
    </head>
    <body>
        <h1>Resultado da pergunta</h1>
        <p>{{ pergunta.texto }}</p>

        <ul>
            {% for opcao in pergunta.opcao_set.all %}
            <li>
                {{ opcao.texto }} = {{ opcao.votos }}
            </li>
            {% endfor %}
        </ul>
        <hr/>
        <a href="{% url 'main:detalhes' pergunta.id %}">Detalhes da enquete</a>
        <a href="{% url 'main:index' %}">Página inicial</a>
    </body>
</htmL>