enquete/catalogo/urls.py
from django.urls import path
from . import views

app_name = 'catalogo'

urlpatterns = [
    path('', views.index, name='index'),
    path('autor/<str:autor>/texto/<str:titulo>', views.texto, name='texto'),
    path('autor/<str:username>', views.autor, name='autor'),
    path('categoria/<str:nome>', views.categoria, name='categoria'),
    path('escrita', views.escrita, name='escrita'),
    path('publicar', views.publicar, name='publicar'),
    path('deletar', views.deletar, name='deletar'),
    path('categorias', views.categorias, name='categorias'),
    path('editar/<int:texto_id>', views.editar, name='editar'),
    path('alterar_texto', views.alterar_texto, name='alterar_texto'),
    path('cadastro', views.cadastro, name='cadastro'),
    path('criar_conta', views.criar_conta, name='criar_conta'),
    path('editar_perfil', views.editar_perfil, name='editar_perfil'),
    path('alterar_perfil', views.alterar_perfil, name='alterar_perfil'),
    path('alterar_senha', views.alterar_senha, name='alterar_senha'),
    path('alterar_imagem_perfil', views.alterar_imagem_perfil, name='alterar_imagem_perfil'),
    path('remover_imagem_perfil', views.remover_imagem_perfil, name='remover_imagem_perfil'),
]

enquete/enquete/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('catalogo/', include('catalogo.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

enquete/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('enquete',views.EnqueteView.as_view(), name='enquete'),
    path('enquete/<int:pk>', views.DetalhesView.as_view(), name='detalhes'),
    path('enquete/<int:pk>/resultado', views.ResultadoView.as_view(), name='resultado'),
    path('enquete/<int:id_pergunta>/votar', views.votacao, name='votacao'),
    path('autor/<int:id_autor>', views.autor, name='autor'),
]

enquete/catalogo/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Categoria(models.Model):
    nome = models.CharField(max_length=200)
    def __str__(self):
        return self.nome

class Texto(models.Model):
    titulo = models.CharField(max_length=200)
    texto = models.TextField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    publico = models.BooleanField(default=False)
    data_publicacao = models.DateTimeField(default=timezone.now())
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    imagem = models.ImageField(upload_to='imagens/textos', blank=True)

    def __str__(self):
        return self.titulo

enquete/catalogo/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect, redirect
from django.http import HttpResponse, Http404
from .models import Texto, Categoria
from django.urls import reverse
from django.contrib.auth.models import User
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate
# Create your views here.

@login_required
def index(request):
    return render(request, 'catalogo/index.html', {})

def texto(request, autor , titulo):
    try:
        texto = Texto.objects.get(Q(autor__username=autor)&Q(titulo=titulo))
    except:
        raise Http404('Texto não encontrado')
    if((request.user == texto.autor) | texto.publico):
        context = {
            'texto':texto,
        }
        return render(request, 'catalogo/texto.html', context)
    raise Http404()

def autor(request, username):
    autor = get_object_or_404(User, username = username)
    if((request.user == autor)):
        textos = Texto.objects.filter(autor = autor).order_by('-data_publicacao')
    else:
        textos = Texto.objects.filter(Q(autor = autor)&Q(publico = True)).order_by('-data_publicacao')
    context = {
        'textos':textos,
    }
    return render(request, 'catalogo/autor.html', context)

def categoria(request, nome):
    categoria = get_object_or_404(Categoria, nome = nome)
    textos = Texto.objects.filter(Q(autor = request.user)&Q(categoria = categoria)).order_by('-data_publicacao')
    context = {
        'textos':textos,
        'categoria':categoria,
    }
    return render(request, 'catalogo/categoria.html', context)

@login_required
def publicar(request):
    titulo = request.POST['titulo']
    texto = request.POST['texto']
    categoria_id = request.POST['categoria']
    categoria = get_object_or_404(Categoria, id=categoria_id)
    publico = False
    if 'publico' in request.POST:
        publico = True
    try:
        texto = Texto.objects.get(Q(autor=request.user)&Q(titulo=titulo))
    except:
        texto = Texto(
            titulo = titulo,
            texto = texto,
            autor = request.user,
            categoria = categoria,
            publico = publico
        )
        if 'imagem' in request.FILES:
            imagem = request.FILES['imagem']
            texto.imagem = imagem
        texto.save()
        return HttpResponseRedirect(reverse('catalogo:texto', kwargs={'autor': request.user.username, 'titulo':titulo}))
    else:
        raise Http404("Já existe um texto com esse título. Tente com outro diferente.")

def alterar_texto(request):
    titulo = request.POST['titulo']
    texto_id = request.POST['texto-id']
    texto_txt = request.POST['texto']
    categoria_id = request.POST['categoria']
    categoria = get_object_or_404(Categoria, id=categoria_id)
    publico = False
    if 'publico' in request.POST:
        publico = True
    try:
        texto = Texto.objects.get(Q(autor=request.user)&Q(titulo=titulo)&~Q(id=texto_id))
    except:
        texto = get_object_or_404(Texto, id=texto_id)
        texto.titulo = titulo
        texto.texto = texto_txt
        texto.categoria = categoria
        texto.publico = publico
        texto.save()
        return HttpResponseRedirect(reverse('catalogo:texto', kwargs={'autor': request.user.username, 'titulo':titulo}))
    else:
        raise Http404('Já existe outro texto com o mesmo título no seu perfil')

@login_required
def escrita(request):
    categorias = Categoria.objects.all()
    context = {
        'categorias':categorias,
    }
    return render(request, 'catalogo/escrita.html', context)

@login_required
def deletar(request):
    texto_id = request.POST['texto-id']
    texto = get_object_or_404(Texto, id=texto_id)
    if texto.autor == request.user:
        if texto.imagem:
            texto.imagem.delete()
        texto.delete()
        return redirect('autor/'+request.user.username)
    else:
        raise Http404()

def categorias(request):
    categorias = Categoria.objects.all()
    context = {
        'categorias':categorias,
    }
    return render(request, 'catalogo/categorias.html', context)

'''
def editar(request):
    texto_id = request.POST['texto-id']
    texto = get_object_or_404(Texto, id=texto_id)
    if texto.autor == request.user:
        texto.editar()
        return redirect('autor/'+request.user.username)
    else:
        raise Http404()
'''

def editar(request, texto_id):
    texto = get_object_or_404(Texto, id=texto_id)
    categorias = Categoria.objects.all()
    context = {
        'categorias':categorias,
        'texto':texto,
    }
    return render(request, 'catalogo/escrita.html', context)


def cadastro(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('catalogo:index'))
    return render(request, 'registration/cadastro.html')

def criar_conta(request):
    username = request.POST['username']
    nome = request.POST['nome']
    sobrenome = request.POST['sobrenome']
    senha = request.POST['senha']
    try:
        user = User.objects.get(username=username)
    except:
        user = User(
            username = username,
            first_name = nome,
            last_name = sobrenome,
        )
        user.set_password(senha)
        user.save()
        return HttpResponseRedirect(reverse('catalogo:autor', kwargs={'username': request.user.username}))
    else:
        context ={
            'nome':nome,
            'sobrenome':sobrenome,
            'username':username,
            'username_ja_utilizado':True,
        }
        return render(request, 'registration/cadastro.html', context)

@login_required
def editar_perfil(request):
    return render(request, 'catalogo/editar_perfil.html')

@login_required
def alterar_perfil(request):
    nome = request.POST['nome']
    sobrenome = request.POST['sobrenome']
    username = request.POST['username']
    try:
        user = User.objects.get(Q(username=username)&~Q(id=request.user.id))
    except:
        user = request.user
        user.first_name = nome,
        user.last_name = sobrenome,
        user.username = username,
        user.save()
        mensagem_de_sucesso = "Perfil alterado com êxito!!"
        context = {
            'mensagem_de_sucesso':mensagem_de_sucesso,
        }
        return render(request, 'catalogo/alterar_perfil.html', context)
    else:
        mensagem_de_erro = "Nome já existe. Por favor, tente outro."
        context = {
            'mensagem_de_erro':mensagem_de_erro,
        }
        return render(request, 'catalogo/alterar_perfil.html', context)

@login_required
def alterar_senha(request):
    senha_atual = request.POST['senha-atual']
    nova_senha = request.POST['nova-senha']
    if request.user.check_password(senha_atual):
        request.user.set_password(nova_senha)
        request.user.save()
        authenticate(username = request.user.username, password=nova_senha)
        login(request, request.user)
        mensagem_de_sucesso = "Senha alterado com êxito!!"
        context ={
            'mensagem_de_sucesso':mensagem_de_sucesso,
        }
        return render(request, 'catalogo/alterar_perfil.html', context)
    else:
        mensagem_de_erro = "A senha está incorreta. Por favor, tente novamente."
        context = {
            'mensagem_de_erro':mensagem_de_erro,
        }
        return render(request, 'catalogo/alterar_perfil.html', context)


@login_required
def alterar_imagem_perfil(request):
    if 'imagem' in request.FILES:
        imagem = request.FILES['imagem']
        if request.user.autor.imagem_perfil:
            request.user.autor.imagem_perfil.delete()
        request.user.autor.imagem_perfil = imagem
        request.user.autor.save()
    return HttpResponseRedirect(reverse('catalogo:autor', kwargs={'username': request.user.username}))


@login_required
def remover_imagem_perfil(request):
    if request.user.imagem_perfil:
        request.user.autor.imagem_perfil.delete()
    return HttpResponseRedirect(reverse('catalogo:autor', kwargs={'username': request.user.username}))

enquete/catalogo/templates/catalogo/autor.html
{% extends 'catalogo/base.html' %}
{% block titulo %}{{ autor.username }}{% endblock %}
{% block content %}
<h1>{{ autor.username }}</h1>
<ul>
    {% for texto in textos %}
    <li>
        <a href="{% url 'catalogo:texto' texto.autor.username texto.titulo %}">
            {% if texto.imagem %}
            <img style="width:400px;" src="{{ texto.imagem.url }}">
            {% endif %}
            <h2>{{ texto.titulo }}</h2>
            <h3>{{ texto.texto }}</h3>
        </a>
    </li>
    {% endfor %}
</ul>




{% endblock %}

enquete/catalogo/templates/catalogo/base.html
{% load static %}
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block titulo %}<a href="{% url 'catalogo:index' %}">Catálogo de textos</a>{% endblock %}
        </title>
    </head>
    <body>
        <header>
            {#<a href="{% url 'catalogo:index' %}" class='link-principal'>#}
                Catalogo
            </a>
            <nav>
            {% if user.is_authenticated %}
            <a href="{% url 'catalogo:escrita' %}">Novo texto</a>
            <a href="{% url 'catalogo:autor' user.username %}">Meu Perfil</a>
            <a href="{% url 'catalogo:alterar_perfil' %}">Alterar Perfil</a>
            {#<a href="{% url 'logout' %}">Sair</a>#}
            {% else %}
            <a href="{% url 'login' %}">Entrar</a>
            <a href="{% url 'catalogo:cadastro' %}">Criar Conta</a>
            {% endif %}
            </nav>
        </header>
        <div class='conteudo'>
            {% block content %}{% endblock %}
        </div>
    </body>
</html>

enquete/catalogo/templates/catalogo/categoria.html
{% extends 'catalogo/base.html' %}
{% block titulo %}{{ categoria.nome }}{% endblock %}
{% block content %}

<h1>{{ categoria.nome }}</h1>
<ul>
    {% for texto in textos %}
    <li>
        <a href="{% url 'catalogo:texto' texto.autor.username texto.titulo %}">
            {% if texto.imagem %}
            <img style="width:400px;" src="{{ texto.imagem.url }}">
            {% endif %}
            <h2>{{ texto.titulo }}</h2>
            <h3>{{ texto.texto }}</h3>
        </a>
    </li>
    {% endfor %}
</ul>




{% endblock %}

enquete/catalogo/templates/catalogo/categorias.html
{% extends 'catalogo/base.html' %}
{% block titulo %}Categorias{% endblock %}
{% block content %}
<h1>Categorias</h1>
<ul>
{% for categoria in categorias %}
    <li>
        <a href="{% url 'catalogo:categoria' categoria.nome %}">{{ categoria.nome }}</a>
    </li>
{% endfor %}
</ul>
{% endblock %}

enquete/catalogo/templates/catalogo/escrita.html
{% extends 'catalogo/base.html' %}
{% block titulo %}Novo Texto{% endblock %}
{% block content %}
<h1>Novo texto</h1>
<form enctype="multipart/form-data" method="post" action="{% if texto %}{% url 'catalogo:alterar_texto' %}{% else %}{% url 'catalogo:publicar' %}{% endif %}">
    {% csrf_token %}
    {% if texto %}
    <input type="hidden" name="texto-id" value="{{ texto.id }}">
    {% endif %}
    <label for="titulo">Título</label>
    <input type="text" value="{{ texto.titulo }}" name="titulo"><br>
    <label for="texto">Texto</label>
    <textarea name="texto">{{ texto.texto }}</textarea><br>
    <label for="publico">Publico</label>
    <input type="checkbox" name="publico" {% if texto.publico %}checked{% endif %}><br>
    <label for="imagem">Imagem(Opcional):</label>
    <input type="file" accept="image/x-png,image/gif,image/jpeg" name='imagem'><br>
    <label for="categoria">Categoria</label>
    <select name="categoria">
        {% for categoria in categorias %}
            <option {% if categoria == texto.categoria %}selected{% endif %} value="{{ categoria.id }}">{{ categoria.nome }}</option>
        {% endfor %}
    </select><br>
    <input type="submit" value="publicar">
</form>


{% endblock %}

enquete/catalogo/templates/catalogo/index.html
{% extends 'catalogo/base.html' %}
{% block titulo %}Página Inicial{% endblock %}
{% block content %}
<h1>Catálogo de Textos</h1>
<a href="{% url 'catalogo:escrita' %}">Escrever novo texto</a><br>
<a href="{% url 'catalogo:autor' user.username %}">Meus Textos</a><br>
<a href="{% url 'catalogo:categorias' %}">Categorias</a>

{% endblock %}

enquete/catalogo/templates/catalogo/texto.html
{% extends 'catalogo/base.html' %}
{% block titulo %}{{ texto.titulo }}{% endblock %}
{% block content %}
<h1>{{ texto.titulo }}</h1>
<h2>{{ texto.data }}</h2>
{% if texto.imagem %}
<img style="width:400px;" src="{{ texto.imagem.url }}">
{% endif %}
<p>{{ texto.texto }}</p>
<a href="{% url 'catalogo:autor' texto.autor.username %}">{{ texto.autor.username }}</a>
<a href="{% url 'catalogo:categoria' texto.categoria.nome %}">{{ texto.categoria.nome }}</a><br>
{% if texto.publico %}
<u>Este texto é público.</u><br>
{% endif %}

{% if user == texto.autor %}
    <form method="post" action="{% url 'catalogo:deletar' %}">
        {% csrf_token %}
        <input type="hidden" name="texto-id" value="{{ texto.id }}">
        <input type="submit" value="Deletar texto">
    </form>

    <a href="{% url 'catalogo:editar' texto.id %}">
        <button>Editar</button>
    </a>

{% endif %}

{% endblock %}